# Generated by Django 5.1.2 on 2024-11-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('VH', 'VulnHub'), ('HTB', 'HackTheBox')], max_length=3)),
                ('operating_system', models.CharField(max_length=20)),
                ('html_writeup', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
