# Generated by Django 5.1.2 on 2024-11-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacklog', '0002_log_updated_at_alter_log_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tags',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
