# Generated by Django 5.1.2 on 2024-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacklog', '0003_log_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
