# Generated by Django 5.1.2 on 2025-01-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacklog', '0009_tip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
