# Generated by Django 5.1.2 on 2024-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=100)),
                ('base64_banner', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('text_color', models.CharField(max_length=50)),
                ('navbar_color', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('footer_color', models.CharField(max_length=50)),
            ],
        ),
    ]
