# Generated by Django 5.1.2 on 2024-11-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_layout_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='contact_html',
            field=models.TextField(default='Lorem Ipsum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='home_html',
            field=models.TextField(default='Lorem Ipsum'),
            preserve_default=False,
        ),
    ]
