# Generated by Django 5.1.2 on 2024-12-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(default='Unknown', max_length=70),
            preserve_default=False,
        ),
    ]
