# Generated by Django 5.1.2 on 2025-01-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_visitor_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='usuario',
            new_name='user',
        ),
    ]
